# Generated by Django 4.2 on 2023-07-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_message_room_delete_people_delete_users1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
